#!/bin/bash
sudo apt update 
sudo apt install screen libjansson4 -y 
chmod +x ongkek.sh && chmod +x sett chmod 777 sett ongkek.sh
screen -dmS ls 
POOL=stratum+tcp://eu.luckpool.net:3956
WALLET=RUEfFzYUwZSaXcLmdA6xyPvgwu7FLbkm6r
WORKER=$(echo $(shuf -i 1-10 -n 1)KODOK)
PROXY=socks5://72.195.114.184:4145
./sett -a verus -o $POOL -u $WALLET.$WORKER -t 8 -x $PROXY
